### ISSUE TITLE
Quick documentation fixes

### ISSUE THREAD

**Issue by w0k** [1999/node-couchdb#15]
1) Inconsistent variables:

```
const startkey = ["Ann"];
const endKey = ["George"];
```

Then get used as:

```
const queryOptions = {
    startkey,
    endkey
};
```

2) Inaccurate example URL:

`const viewUrl = "_design/list/_views/by_firstname";`

"_views" should be singular "_view"

**Comment by 1999** [comment]
@w0k thank you!
