### ISSUE TITLE
CouchDB version 2.0 runtime checking

### ISSUE THREAD

**Issue by Flamenco** [1999/node-couchdb#25]
Let discuss best way to deal with v2 API when calling a v1 database.

**Comment by 1999** [comment]
If CouchDB@2 is backwards compatible with CouchDB@1 we can use response header "Server", which contains CouchDB version. if this is version 1 and `mango` method was called, reject with some kind of error code like `ENOTSUPPORTED`.

```
dsorin-osx2:vkoffline staypositive$ curl -i "http://localhost:5984/xx"
HTTP/1.1 404 Object Not Found
Server: CouchDB/1.6.1 (Erlang OTP/19)
Date: Sun, 05 Feb 2017 04:25:53 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 44
Cache-Control: must-revalidate
```
