### ISSUE TITLE
Update document without removing its old contents

### ISSUE THREAD

**Issue by HarounAns** [1999/node-couchdb#30]
I'd like to update a document by passing in new fields that I want added but leaving the old ones.

For instance my json doc may be like this 
{
    id = xxxxxxxxxxx,
    rev = yyyyyyyyyyy
    filename = foo
}

and I want to update to include new fields but not remove the old ones, without having to pass the old fields in again like this:

couch.update(dbName, {
 date = 01/23/45
})

I guess this may be more of a feature request if it is not already implementable

**Comment by 1999** [comment]
I guess what you're talking about is PATCH support for CouchDB which is still not implemented: https://stackoverflow.com/questions/4132702/how-to-update-a-documents-record-field-in-couchdb

However you can use [document update handlers](https://wiki.apache.org/couchdb/Document_Update_Handlers) for this.
