### ISSUE TITLE
How to use with Cloudant

### ISSUE THREAD

**Issue by HarounAns** [1999/node-couchdb#33]
Hi, I've been using this API with my local database on Couch and it has been working great. Now that my application is finished and running, I have replicated my database to Cloudant. What changes do I need to make in order to use with my remote database in terms of Login and Authentication?

**Comment by 1999** [comment]
Hi @HarounAns. I haven't been working with CLoudant's CouchDB recently but from what I remember you should set up host name and auth credentials:

```javascript
const couch = new NodeCouchDb({
    host: 'couchdb.cloudant',
    protocol: 'https',
    port: 6984,
    auth: {
        user: 'login',
        pass: 'secret'
    }
});
```

**Comment by HarounAns** [comment]
6984? Is that the port that Cloudant uses? And if you are not using Cloudant, what ways would you host the database remotely then? Any recommendations?

**Comment by 1999** [comment]
6984 is the default CouchDB port, not sure if Cloudant is using different port. As for hosting the database unfortunately I can't give you some up-to-date advice because unfortunately last time I've been working with CouchDB was more than 3 years ago and it has changed much since then.

**Comment by gjgd** [comment]
For anyone else facing this problem, for a Cloudant url of this form: `https://USER:PASS@HOST` the correct code to connect to it is:

```
const NodeCouchDb = require('node-couchdb');
// This is a fake URL
const COUCHDB_REMOTE =
  'https://2eb50eeb3b74-a2d6-4d06-ab14-2eb50eeb3b74-bluemix:2eb50eeb3b742eb50eeb3b742eb50eeb3b74@2eb50eeb3b74-a2d6-4d06-ab14-2eb50eeb3b74-bluemix.cloudantnosqldb.appdomain.cloud';

const urlRegex = /https:\/\/(.*):(.*)@(.*)\/(.*)/;
const parts = urlRegex.exec(COUCHDB_REMOTE);
const couch = new NodeCouchDb({
  host: parts[3],
  protocol: 'https',
  port: 443,
  auth: {
    user: parts[1],
    pass: parts[2],
  },
});


(async () => {
  await couch.listDatabases().then(console.log).catch(console.log);
})();

```
