### ISSUE TITLE
Provide Typings for Typescript

### ISSUE THREAD

**Issue by Weber-D** [1999/node-couchdb#36]
It seems that no typings are included nor the corresponding package `@types/node-couchdb` exists. For me as a Typescript developer, this is unusable and I have to look for alternative librarys. So please provide typings for your library, so that we can use them strongly typed.

**Comment by 1999** [comment]
This is OSS so you're welcome to send a PR to this package with declaration file(s).

**Comment by 1999** [comment]
Btw as far as I know common way to provide typings is either to provide them with the package itself or contribute to DefinitelyTyped. I also contributed to couple of definitions there so if you can do that for node-couchdb I will be more than happy to add info about it to the README.
