### ISSUE TITLE
No way to user a login account

### ISSUE THREAD

**Issue by zeus3rd** [1999/node-couchdb#4]
CouchDB by default disallows database creation/deletion without admin rights and node-couchdb does not have any method of authenticating with the server (making createDatabase() and dropDatabase() unusable unless security is removed)

**Comment by sambengtson** [comment]
+1  I'm assuming there is no current plans to resolve this?

**Comment by Ava7** [comment]
+1

**Comment by 1999** [comment]
@zeus3rd @sambengtson @Ava7 guys what do you think of adding user/pass propertes to node-couchdb constructor?

**Comment by sambengtson** [comment]
Yeah that would be good.
