### ISSUE TITLE
issue with list database command

### ISSUE THREAD

**Issue by VenkateshSrini** [1999/node-couchdb#6]
when we use the list database command we are getting the below issue 
undefined:1
[object Object]
 ^
SyntaxError: Unexpected token o
    at Object.parse (native)

This is primarily happening because the response from http://localHost:5984/_all_dbs is a JSON. and the library is again doing a JSON.Parse of the response. So the change in the function has to be made to remove the JSON.parse.

**Comment by 1999** [comment]
Fixed in #5
